---
title: "Week 9 Assignment"
output: html_document
date: "2023-03-19"
---

## All together now

### Loading tidyverse and ggrepel (may need to install the first time using install.packages)

```{r}

```

```{r}
midwest %>% 
  select(poptotal, percbelowpoverty, county, state) %>% unite(county_state, county, state, sep = ", ") %>% ggplot(aes(x = poptotal, y = percbelowpoverty, label = county_state)) + geom_point() +geom_text_repel(max.overlaps = 2)
```

## Independently

```{r}
library(tidyverse)
library(ggrepel)

us_rent_income %>% 
  select(-moe) %>% 
  spread(variable, estimate) %>% 
  ggplot(aes(x = income, y = rent, label = NAME)) +
  geom_point() +
  geom_text()

us_rent_income %>% 
  select(-moe) %>% 
  spread(variable, estimate) %>% 
  ggplot(aes(x = income, y = rent, label = NAME)) +
  geom_point() +
  geom_text_repel()

us_rent_income %>% 
  select(-moe) %>% 
  spread(variable, estimate) %>% 
  mutate(rent = rent * 12) %>% 
  mutate(prop_of_income = rent/income) %>% 
  mutate(NAME = ifelse(prop_of_income > .50, NAME, NA)) %>% 
  ggplot(aes(x = income, y = rent, label = NAME)) +
  geom_point() +
  geom_text(hjust = 0, nudge_x = 100)
```