---
title: "Data Viz Teardown"
author: "Colorful Student"
date: '2022-12-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

1. Fill vs Color

```{r}
example_data %>%
  ggplot(aes(x=numbers, y=letters, fill=letters))+
  geom_col()
```

```{r}
example_data %>%
  ggplot(aes(x=numbers, y=letters, color=letters))+
  geom_col()
```

```{r}
example_data %>%
  ggplot(aes(x=numbers, y=letters, fill=letters))+
  geom_point(size=8)
```

```{r}
example_data %>%
  ggplot(aes(x=numbers, y=letters, color=letters))+
  geom_point(size=8)
```

2. What if fill is numeric?

```{r}
set.seed(1983)
example_data <- data.frame(letters=LETTERS[1:5], numbers=sample(5:20, 5))

example_data %>%
  ggplot(aes(x=numbers, y=letters, fill=numbers))+
  geom_col()
```


3. Which function below is controlling the colors?

```{r}
my_colors <- c("A" = utk_color("orange"),
                             "B" = utk_color("valley"),
                             "C" = utk_color("energy"),
                             "D" = utk_color("regalia"),
                             "E" = utk_color("fountain"))

example_data %>%
  ggplot(aes(x=numbers, y=letters, color=letters))+
  geom_point(size=8)+
  scale_fill_manual(values = my_colors)+
  scale_color_manual(values = my_colors)
```


4. What does `scale_fill_gradient` do?

```{r}
example_data %>%
  ggplot(aes(x=numbers, y=reorder(letters, numbers), fill=numbers))+
  geom_col()+
  scale_fill_gradient(low=utk_color("fountain"), high=utk_color("energy"))
```

5. What does `scale_fill_gradientn` do?

```{r}
set.seed(123)
example_data <- data.frame(letters=LETTERS[1:5], numbers=sample(0:100, 5))

example_data %>%
  ggplot(aes(x=numbers, y=reorder(letters, numbers), fill=numbers))+
  geom_col()+
  scale_fill_gradientn(colors=utk_color("leconte", "fountain", "energy"))
```

6. What does `scale_fill_gradient2` do?

```{r}
set.seed(123)
example_data <- data.frame(letters=LETTERS[1:5], numbers=c(0, sample(-10:10, 5)))

example_data %>%
  ggplot(aes(x=numbers, y=reorder(letters, numbers), fill=numbers))+
  geom_col()+
  scale_fill_gradient2(high=utk_color("orange"), mid="grey70", low=utk_color("fountain"))
```

7. What steps were used to create the graph's highlight?

```{r}
set.seed(1983)
example_data <- data.frame(letters=LETTERS[1:5], numbers=sample(5:20, 5))

example_data %>%
  ggplot(aes(x=numbers, y=reorder(letters, numbers), fill=letters))+
  geom_col(show.legend = FALSE)+
  scale_fill_manual(values=c("E" = utk_color("orange"), "grey90"))+
  theme_minimal()+
  labs(y=NULL,
       title="A Plot Demonstrating Highlighting")
```
