---
title: "Week 10 Assignment"
author: ""
date: ''
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
```

This week's assignment is quite simple. You are going to re-ruse some of your old graphs in order to practice making compound graphics and small multiples and using annotations.


## Compound Plots with patchwork

Using a previous data set and related analyses and/or visualizations, combine separate plots using `patchwork`. For some additional functionality (or examples), check out its documentation: https://patchwork.data-imaginist.com/index.html



## Small Multiples with facet_wrap()

Using a previous data set (and analysis), develop a data visualization that uses small multiples. To add a little pizazz and style your facets, consider consulting these resources:

- http://www.cookbook-r.com/Graphs/Facets_(ggplot2)/
- https://www.datanovia.com/en/blog/how-to-change-ggplot-facet-labels/


## Annotations

Again using a previous data set and related analyses and/or visualizations, add two or more annotation layers to a plot OR use gghighlight.


