---
title: 'ggplot2 Prework: Data Wrangling'
author: "XXX"
date: "`r Sys.Date()`"
output: html_document
---
<!--- Put your name in the author YAML field.--->
<!--- Load the tidyverse library in the setup chunk.--->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

<!--- Read in the `tidykids.csv` file, delete the first column `...1` and
clean the column names.--->
```{r read-in-data}
tidykids <- read_csv("tidykids.csv")

tidykids <- tidykids |>
  select(-...1) |> # Don't think you need this anymore
  janitor::clean_names()
```

<!--- Look at the data and the codebook. (Link to codebook: https://jrosen48.github.io/tidykids/articles/tidykids-codebook.html). 
What does each variable represent? In what units? -->

Type your answer here!

<!-- Example: You are only interested in the data for 2016. Filter the data for 2016. -->
```{r filter-2016}
tidykids |>
  filter(year == 2016)
```

<!-- You want to create a new region variable. Create this using what we learned last week. -->
```{r create-region-variable}
tidykids <- tidykids |>
  mutate(region = case_when(
    state %in% c("Maine", "New Hampshire", "Vermont", "Massachusetts", "Rhode Island", 
                 "Connecticut", "New York", "New Jersey", "Pennsylvania") ~ "Northeast",
    state %in% c("Ohio", "Indiana", "Illinois", "Michigan", "Wisconsin", "Minnesota",
                 "Iowa", "Missouri", "North Dakota", "South Dakota", "Nebraska", "Kansas") ~ "Midwest",
    state %in% c("Delaware", "Maryland", "Virginia", "West Virginia", "North Carolina", 
                 "South Carolina", "Georgia", "Florida", "Kentucky", "Tennessee", 
                 "Alabama", "Mississippi", "Arkansas", "Louisiana", "Oklahoma",
                 "Texas", "District of Columbia") ~ "South",
    state %in% c("Montana", "Idaho", "Wyoming", "Colorado", "New Mexico", "Arizona", 
                 "Utah", "Nevada", "California", "Oregon", "Washington", "Hawaii",
                 "Alaska") ~ "West"
  ))
```

<!-- You want to focus only on library expenditures. Look at the codebook to find the variable name for library expenditures and filter for it.-->

```{r filter-library-expenditures}
tidykids_lib <- tidykids |>
  filter(variable == "lib")
```

<!-- You want to summarize(mean and std. dev) these library expenditures(inf_adj_perchild) by region. Do this.-->
```{r summarize-by-region}
tidykids_lib |>
  group_by(region) |>
  summarize(mean = mean(inf_adj_perchild, na.rm = TRUE),
            sd = sd(inf_adj_perchild, na.rm = TRUE))
```
