---
title: 'ggplot2 Prework: Data Wrangling'
author: "XXX"
date: "`r Sys.Date()`"
output: html_document
---
<!--- Put your name in the author YAML field.--->
<!--- Load the tidyverse library in the setup chunk. Set message and warning to false in the setup chunk.--->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!--- Read in the `tidykids.csv` file, delete the first column `...1` and
clean the column names.--->
```{r read-in-data}

```

<!--- Look at the data and the codebook. (Link to codebook: https://jrosen48.github.io/tidykids/articles/tidykids-codebook.html). 

How many variables are available in the tidykids dataset? How many distinct levels of the variable `variable` are there? -->

Type your answer here!

<!-- What does each variable represent? In what units?  -->

Type your answer here!

<!-- Example: You are only interested in the data for 2016. Filter the data for 2016. -->
```{r filter-2016}

```

<!-- You want to create a new region variable. Create this using what we learned last week. Note that this code is provided in Canvas because it is long to type.-->
```{r create-region-variable}

```

<!-- You want to focus only on library expenditures. Look at the codebook to find the variable name for library expenditures and filter for it.-->

```{r filter-library-expenditures}

```

<!-- You want to summarize(mean and std. dev) these library expenditures(inf_adj_perchild) by region for 2016. Do this.-->
```{r summarize-by-region}

```
